# Generated by Django 5.2.1 on 2025-07-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drawpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='drawsteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepno', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('steptext', models.CharField(verbose_name=300)),
                ('stepcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepdiscription', to='api.drawpage')),
            ],
        ),
    ]
