# Generated by Django 5.2.1 on 2025-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawsteps',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
