# Generated by Django 5.2.1 on 2025-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_drawsteps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawpage',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
